<?php

/**
* Implements hook_action_info().
*/
function unblock_action_action_info() {
return array(
'unblock_action_unblock_user_action' => array(
'label' => t('Approve Account'),
'type' => 'user',
'configurable' => FALSE,
'triggers' => array('any'),
),
);
}

/**
* Unblocks a user, defaulting to the current user.
*
* @ingroup actions
*/
function unblock_action_unblock_user_action($entity, $context = array()) {
// First priority: If there is a $entity->uid, unblock that user.
// This is most likely a user object or the author if a node or comment.
if (isset($entity->uid)) {
$uid = $entity->uid;
}
// Otherwise get user ID from the context.
elseif (isset($context['uid'])) {
$uid = $context['uid'];
}
$account = user_load($uid);
$account = user_save($account, array('status' => 1));
watchdog('action', 'Unblocked user %name.', array('%name' => $account->name));
}